# See: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

disableStartupPopups: true
notARepository: quit
git:
  disableForcePushing: true
gui:
  showBottomLine: false
  showRandomTip: false
  showPanelJumps: false
  theme:
    selectedLineBgColor:
      - black
  branchColorPatterns:
    ^main$: red
    ^(dev|staging)$: magenta
    ^(feat|(|hot)fix)\/: blue
    ^\d+-: blue
